/**
 * Business details. You normally do NOT edit this file:
 * change `public/config.js` instead (in the built site it is `config.js` in the site folder).
 * Anything left empty is simply not shown on the website.
 */
const runtime = (typeof window !== 'undefined' && window.TALEEM_CONFIG) || {};

// Use the value from config.js when it is filled in, otherwise fall back to the default (null = hidden).
const pick = (defaults, overrides = {}) =>
  Object.fromEntries(Object.entries(defaults).map(([k, v]) => [k, overrides?.[k] || v]));

export const site = {
  name: 'Taleem Tech',
  tagline: 'Digital solutions for modern businesses',

  contact: pick({ email: null, phone: null, whatsapp: null, address: null }, runtime.contact),
  social: pick({ instagram: null, facebook: null, linkedin: null, youtube: null }, runtime.social),

  // Set showPrices to false in config.js to hide every ₹ amount.
  showPrices: typeof runtime.showPrices === 'boolean' ? runtime.showPrices : true,
};
